# Generated by Django 4.2 on 2023-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='photos/cartegories')),
            ],
            options={
                'verbose_name': 'cartegory',
                'verbose_name_plural': 'cartegories',
            },
        ),
    ]
