# Generated by Django 4.2 on 2023-04-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartegory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartegory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
