# Generated by Django 4.2 on 2023-04-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartegory', '0002_alter_cartegory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='photos/product')),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartegory.cartegory')),
            ],
        ),
    ]
